## docker-compose up -d
version: "2"
services:
  jenkins:
    image: "jenkins:latest"
    ports:
      - 8080:8080
      - 50000:50000
    restart: "always"
    volumes:
      - ./data-jenkins:/var/jenkins_home